language: ruby
rvm:
  - 2.0.0
  - 2.1.3
  - jruby
  - jruby-head
  - ruby-head
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--2.0"
  allow_failures:
    - rvm: jruby
before_script:
  - sudo rm /dev/random
  - sudo ln -s /dev/urandom /dev/random
